name: tox

on:
  # Trigger the tests workflow on push or pull requests.
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  run_tox:
    name: tox -e ${{ matrix.toxenv }} (${{matrix.python-version}} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
        os:
          - "ubuntu-latest"
        toxenv:
          - "blue"
          - "flake8"
          - "docs"
          - "twine_check"
          - "py38"
        include:
          - python-version: 3.7
            os: ubuntu-latest
            toxenv: py37
          - python-version: 3.9
            os: ubuntu-latest
            toxenv: py39
          - python-version: "3.10"
            os: ubuntu-latest
            toxenv: py310
          - python-version: "3.11"
            os: ubuntu-latest
            toxenv: py311
          - python-version: "3.11"
            os: macos-latest
            toxenv: py311
          - python-version: "3.11"
            os: windows-latest
            toxenv: py311

    # Steps to run in each job.
    # Some are GitHub actions, others run shell commands.
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage tox
          python --version
          pip --version
          tox --version
          coverage --version

      - name: Run tests
        run: tox -e ${{ matrix.toxenv }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: ${{ matrix.toxenv == 'py38' && matrix.os == 'ubuntu-20.04' }}
        with:
          env_vars: PYTHON
          fail_ci_if_error: true

  run_tox_with_postgres:
    name: tox -e ${{ matrix.toxenv }} (${{matrix.python-version}} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 3.8
            os: ubuntu-latest
            toxenv: postgresql
          - python-version: pypy3.9
            os: ubuntu-latest
            toxenv: pypy3_postgresql

    # Run the PostgreSQL database service.
    services:
      # Label used to access the service container.
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: verysecret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Map TCP port 5432 on service container to the host
          - "5432:5432"

    # Steps to run in each job.
    # Some are GitHub actions, others run shell commands.
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
          python --version
          pip --version
          tox --version

      - name: Run tests
        env:
          FALCON_SQLA_POSTGRESQL_URI: postgresql://postgres:verysecret@localhost/postgres
        run: tox -e ${{ matrix.toxenv }}
